### ISSUE TITLE
خارج شدن از برنامه - ویندوز

### ISSUE THREAD

**Issue by Amirmohammadkazemi** [Mehran-Seifalinia/ShareYourFolder#1]
وقتی تو ویندوز (برا من وندوز 10 64 بیت هست) برنامه رو اجرا میکنیم و آی پی و پورت رو میزنیم سریع از برنامه خارج میشه

**Comment by Mehran-Seifalinia** [comment]
# ممنون از اطلاع رسانی
اگه ممکنه خط فرمان ویندوز رو باز کن و به مسیر فایل برو و فایل رو از طریق خط فرمان اجرا کن و اروری که توی خط فرمان نمایش میده رو برای من ارسال کن یا میتونی توی مسیری که فایل قرار داره، مطابق شکل زیر خط فرمان رو باز کنی و فایل رو اجرا کنی. از نتیجه ی اجرا یک عکس برام بفرست یا متنش رو برام ارسال کن. ممنون
<br />
![Issue(1)](https://user-images.githubusercontent.com/70560051/117577389-d3693000-b0fe-11eb-8252-da6451dd8e93.png)

**Comment by Amirmohammadkazemi** [comment]
داداش من خودم مهندسی کامپیوتر میخونم میدونم چجور cmd رو اونجا بیارم😄
باشه برات ایشو میدم

در تاریخ یکشنبه ۹ مهٔ ۲۰۲۱،‏ ۱۹:۴۴ Mehran Seifalinia <
***@***.***> نوشت:

**Comment by Mehran-Seifalinia** [comment]
بله جسارت نکردم، اما باید طوری پاسخ بدم که اگه یه فرد غیر فنی هم با این مشکل مواجه شد، بتونه فرآیند رو انجام بده.
با توجه به مشکل دوم، به نظر میرسه این مشکل بسته شدن برنامه رفع شده و برنامه به درستی اجرا می‌شه، مشکلاتی که در خصوص دانلود فایل‌ها وجود داره رو توی همون ایشیو دوم که ایجاد کردی بررسی می‌کنیم.

**Comment by Amirmohammadkazemi** [comment]
> بله جسارت نکردم، اما باید طوری پاسخ بدم که اگه یه فرد غیر فنی هم با این مشکل مواجه شد، بتونه فرآیند رو انجام بده.
> با توجه به مشکل دوم، به نظر میرسه این مشکل بسته شدن برنامه رفع شده و برنامه به درستی اجرا می‌شه، مشکلاتی که در خصوص دانلود فایل‌ها وجود داره رو توی همون ایشیو دوم که ایجاد کردی بررسی می‌کنیم.

حسن نیت شما رو درک میکنم
این مشکل برطرف شد
فقط همون دومی مونده که تو یه ایشو دیگه مطرح کردم
