### ISSUE TITLE
فرمت دانلود

### ISSUE THREAD

**Issue by Amirmohammadkazemi** [Mehran-Seifalinia/ShareYourFolder#2]
فرمت فایل به صورت زیر دانلود میشه
.download
![image](https://user-images.githubusercontent.com/78997499/117621025-626d5b00-b186-11eb-892d-5f65cf0ce742.png)

**Comment by Mehran-Seifalinia** [comment]
# نیازمند اطلاعات بیشتر
اگه ممکنه فرمت فایلی که داری دانلود می‌کنی
 رو بررسی کن، فرمت فایل دانلودی چیه؟ آیا روی تمام فایل‌‌ها این مشکل وجود داره؟ چون بررسی که کردم مشکلی وجود نداره و فایل دقیقا با فرمتی که وجود داره دانلود میشه.

![Issue(2)](https://user-images.githubusercontent.com/70560051/117632885-bf6f0e00-b192-11eb-806a-c5746fce05ea.png)

**Comment by Amirmohammadkazemi** [comment]
> # نیازمند اطلاعات بیشتر
> اگه ممکنه فرمت فایلی که داری دانلود می‌کنی
> رو بررسی کن، فرمت فایل دانلودی چیه؟ آیا روی تمام فایل‌‌ها این مشکل وجود داره؟ چون بررسی که کردم مشکلی وجود نداره و فایل دقیقا با فرمتی که وجود داره دانلود میشه.
> 
> ![Issue(2)](https://user-images.githubusercontent.com/70560051/117632885-bf6f0e00-b192-11eb-806a-c5746fce05ea.png)

آره روی تمام فایل ها همین مشکلو داره 
خلرج از کامپیوتر هم نمیخونه

**Comment by Mehran-Seifalinia** [comment]
من بررسی کردم و هنوز نتونستم مشکل رو پیدا کنم ولی چندتا ایده دارم که کمک میکنه بهتر بشه مشکل رو بررسی کرد.
اگه ممکنه یک پوشه با چند فایل و فرمت‌های مختلف ایجاد کن و روی تمام فرمت‌ها دانلود کن. اگر مشکلی وجود داشت از یک مرورگر دیگه هم تست کن (ممکنه این مشکل به دلیل کانفیگ خاصی باشه که روی مرورگر فعلی ایجاد شده.)
و اینکه متوجه نشدم منظورت از **خارج از کامپیوتر هم نمی‌خونه** دقیقا چیه؟

**Comment by Mehran-Seifalinia** [comment]
# پاسخ
با بررسی‌های انجام شده به نظر میرسه که مشکل از سمت مرورگر باشه، بیشنهاد برای رفع مشکل دانلود به وسیله‌ی اینترنت دانلود منجر هست.
